### ISSUE TITLE
全棉时代运行问题

### ISSUE THREAD

**Issue by taurus2146** [sudojia/scripts#24]
全棉时代官方自营商城任务执行的时候提示暂未查询到任务,天天种棉花又提示签到失败，当前游戏已经登录了哦,但我其实也没有打开天天种棉花
![image](https://github.com/sudojia/scripts/assets/4773894/aab5772e-bd6f-4bcc-a5fa-99c9b4f8827f)
![Uploading image.png…]()

**Comment by Reverccb** [comment]
我也是 其他脚本都正常 就全棉失败

**Comment by sudojia** [comment]
喵的，token 有效期只有一天，尝试所有办法刷新 token 无果，算了，此脚本 delete
