### ISSUE TITLE
七彩虹500

### ISSUE THREAD

**Issue by Su0515** [sudojia/scripts#26]
![image](https://github.com/sudojia/scripts/assets/124444534/4c2d53ec-8aef-470e-a689-ac7b1572ed55)
如图

**Comment by sudojia** [comment]
500是七彩虹服务器问题，与脚本无关，你可以再重试几遍

![image](https://github.com/sudojia/scripts/assets/86390796/23e1ef36-5b03-4334-a164-be45eabfa166)

**Comment by sudojia** [comment]
> ![image](https://private-user-images.githubusercontent.com/124444534/342534943-4c2d53ec-8aef-470e-a689-ac7b1572ed55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyODM0MDgsIm5iZiI6MTcxOTI4MzEwOCwicGF0aCI6Ii8xMjQ0NDQ1MzQvMzQyNTM0OTQzLTRjMmQ1M2VjLThhZWYtNDcwZS1hNjg5LWFjN2IxNTcyZWQ1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwMjM4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTkzYzZiZjY5ZDNmNzU1MWFlN2E2Yzk3YzhhMmIxOTcxOTdmMTMwZDkzNDdmNDI2NmEyYWEzMjI3Y2I4NTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h86ugQZcaWhU8vphKY4cYiJsaCjfGFaLfn3QLxVGaAk) 如图

500是七彩虹服务器问题，与脚本无关，你可以再重试几遍
![image](https://github.com/sudojia/scripts/assets/86390796/2d881e9f-8965-4f6a-9620-f3efe05570a7)
