### ISSUE TITLE
顺丰快递

### ISSUE THREAD

**Issue by StarSink9** [sudojia/scripts#31]
功能请求

小程序：顺丰速运小程序

入口：顺丰速运+小程序 -> 我的 -> 积分 -> 做任务赚积分
           顺丰速运+小程序 -> 我的 -> 收件兑奖

奖励：每日签到或做任务获得积分，积分可以兑换实物或免单卷

![image](https://github.com/sudojia/scripts/assets/112603695/e6c5390c-ae68-40c9-8569-3606b056d205)
![image](https://github.com/sudojia/scripts/assets/112603695/3aae8314-18fb-47aa-810c-30c3be5f45f6)
![image](https://github.com/sudojia/scripts/assets/112603695/c06d150d-05d5-484f-8f25-ce93870358ce)

**Comment by sudojia** [comment]
这个脚本原本想写的，但是看到别的地方有就没写了，我自己也在跑他的😂，你要的话tg pm我
