### ISSUE TITLE
拉去最新脚本后青龙面板运行需要手动结束

### ISSUE THREAD

**Issue by dsjskeu** [sudojia/scripts#32]
## BUG 提交

**脚本名称**：sudojia_colorful_mall.js,  sudojia_bwtea.js

**问题描述**：

拉去最新脚本后，控制台显示已经执行完毕，但青龙面板还是运行的状态，需要手动结束

**运行环境**：

- **面板/工具**：青龙面板 2.17.4

**附加信息**：

![image](https://github.com/sudojia/scripts/assets/42575327/ceea6caa-338b-47d2-a1e9-da8cad06876f)

![image](https://github.com/sudojia/scripts/assets/42575327/f4edbb82-160b-4be3-9839-6d43b2a97ea3)

**Comment by sudojia** [comment]
好的，我瞅瞅

**Comment by sudojia** [comment]
忘记取消保护了，重新拉库再试试

**Comment by dsjskeu** [comment]
可以了，大佬给力
