### ISSUE TITLE
中国联通

### ISSUE THREAD

**Issue by zestister** [sudojia/scripts#35]
中国联通APP，自动签到以及阅光宝盒领任务刷时长。之前用的拉菲大佬的，但他好像删库了。大佬如果可以的话，四川联通有一个云养熊猫的活动，可以整一下吗？
![IMG_20240701_172732](https://github.com/sudojia/scripts/assets/94108739/18e53721-bf7a-428a-94b7-8f17ca787ccd)
![Screenshot_2024-07-01-17-25-33-420_com sinovatech unicom ui](https://github.com/sudojia/scripts/assets/94108739/4f648838-7f37-448f-8b21-51b4da868058)

**Comment by sudojia** [comment]
[Issues 说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)

很抱歉，你可以搜索下有没有 fork 了那位大佬的库，然后看下能不能 run 起来
