### ISSUE TITLE
大佬能不能添加一个比亚迪app的自动签到啊！求求了

### ISSUE THREAD

**Issue by a9832649464** [sudojia/scripts#36]
## 功能请求

> 请先查看：[Issues 说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)

**网站 / 小程序**：https://xxxx.com / 某某某小程序

**入口**：登录之后右上角签到 / 某某某小程序 -> 我的 -> 签到

**奖励**：每日签到获得积分，积分可以兑换实物

**附加信息**：

- 上传截图
- 任何有助于的其他信息
- 不知名的最好附上官网链接，免得找半天

**Comment by sudojia** [comment]
未按照模板填写，且未查看 [Issues说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)
