### ISSUE TITLE
突然没有kuro的工作流了？

### ISSUE THREAD

**Issue by yinghuashuxiadiyishenqing** [sudojia/scripts#49]
![QQ_1720861474406](https://github.com/user-attachments/assets/51476adc-9a0c-424b-b6b9-bee73478998c)

**Comment by sudojia** [comment]
。。。。因为删了呀

**Comment by yinghuashuxiadiyishenqing** [comment]
> 。。。。因为删了呀

为啥给删了 我还就说咋没自动运行了

**Comment by sudojia** [comment]
> > 。。。。因为删了呀
> 
> 为啥给删了 我还就说咋没自动运行了

GitHub Actions 还是不太放心

**Comment by sudojia** [comment]
后面就自己根据需求，在自己 fork 的仓库添加 actions 文件，改下脚本名和环境变量就好了

**Comment by sudojia** [comment]
所有的 Actions 代码都是一样的，只是脚本名和变量名不一样罢了

**Comment by yinghuashuxiadiyishenqing** [comment]
> 所有 Actions 代码都是一样的，只是脚本名和变量名都没有调用

原来如此 么么
