### ISSUE TITLE
安装依赖显示禁用推荐保护怎么解决啊

### ISSUE THREAD

**Issue by jianghao66351** [sudojia/scripts#58]
![Screenshot_2024-07-28-00-33-33-39_8b7aa5be40a89c6a7df806c347da652a.jpg](https://github.com/user-attachments/assets/11aa1a1e-2c43-44ba-b3b4-e0435aa83d6d)

安装依赖装不上都显示这个界面怎么解决啊大佬

**Comment by s34304** [comment]
我自己装不了看日志是淘宝源证书过期导致的, 禁用证书检测就可以了
