### ISSUE TITLE
多合一无效 貌似其它脚本亦是如此

### ISSUE THREAD

**Issue by lucky-666666** [sudojia/scripts#89]
![36df994e9c57ee8d0d1efdfeb65629be](https://github.com/user-attachments/assets/c6266242-8c1e-45a7-b5b7-c7fcb1aa1657)

**Comment by sudojia** [comment]
![image](https://github.com/user-attachments/assets/97542237-f8ea-44bd-a448-7932a5b68a97)

我怎么试也试不出来，我这里测试没问题，代码逻辑也没问题

![image](https://github.com/user-attachments/assets/3c1d903b-1dd8-4f04-bb0b-4b163513e33b)
